### ISSUE TITLE
Layout Analysis not working

### ISSUE THREAD

**Issue by lferrazzini95** [Transkribus/TranskribusPyClient#5]
Hi,
when I try to make a post request on the 'https://transkribus.eu/TrpServer/rest/LA' function I get a 403 error. I am not sure what could be the problem as I am able to successfully log into my account and look at collections and pages etc.

My parameters look as follows:
```
import` json
import requests
data= json.dumps({"docList" : {
                  "docs" : [ {
                     "docId" : docId,
                     "pageList" : {
                        "pages" : [ {
                           "pageId" : pageId,
                           "regionIds" : [ region.attrib['id'] ]
                        }, {
                           "pageId" : pageId,
                           "tsId" : tsId
                        } ]
                     }
                  } ]
               }
            })

params = json.dumps({'collId': colId,
                     'doBlockSeg': False,
                     'doLineSeg': True,
                     #'doWordSeg' : False,
                     'doPolygonToBaseline': False,
                     'doBaselineToPolygon': False,
                     'jobImpl' : 'CITlabAdvancedLaJob'})

dHeader = {'Cookie':'JSESSIONID=%s'%sid}
dHeader['Content-Type'] = "application/json"
```
And I try to run the following function:
`r = requests.post('https://transkribus.eu/TrpServer/rest/LA', data = data, params = params, headers = dHeader)`

I am not sure if I need a proxy, but if I do should I be able to read data from collections and pages?
Is the proxy only needed for the analyze functions?
Thank you a lot for your help!

Best,
Luca

**Comment by DRRV** [comment]
Hi

The command line for performing LA is do_analyseLayout.py 
(https://github.com/Transkribus/TranskribusPyClient/blob/master/src/TranskribusCommands/do_analyzeLayout.py)

The doc is a bit deprecated but you can have a look :https://github.com/Transkribus/TranskribusPyClient/wiki#LA_Layout_Analysis

**Comment by lferrazzini95** [comment]
Hi Thanks a lot for your very fast response!
I am trying to run the LA on a specific TextRegion. And as far as I was able to tell from the code you send, it is not possible to specify certain TextRegions or am I wrong?
Thank you again for your help!

**Comment by DRRV** [comment]
... need to dig into (very) old memories... :)
it seems that it is possible: you should provide region ids as well: see line 710 in 
https://github.com/Transkribus/TranskribusPyClient/blob/master/src/TranskribusPyClient/client.py

**Comment by lferrazzini95** [comment]
Thank you a lot for looking into that! But if I look at my implementation it should work or am I missing something?
I am passing the data argument in a json format (string in json format) and the parameters as well (I also tried to pass the parameters (params) as a dictionary but this didn't work. Then further in the header I specify the session and the content-type (json).  Shouldn't this in theory work? 
Thank you again for your help and time, I really appreciate it!

**Comment by DRRV** [comment]
I forgot to transform regionids  when converting to xml.
have a look at line 227(do_analyzeLayout.py pull first): when ids are listed, only these regions are processed. when the list is empty, the full page is processed

**Comment by lferrazzini95** [comment]
Thank you for the reply!
So I should call the script as follows:

`python do_analyseLayout.py <colid></colid><docid></docid>[<pages></pages>]<donotblockseq></donotblockseq><donotlineseg></donotlineseg>`

(I took this from the [doc](https://github.com/Transkribus/TranskribusPyClient/wiki#LA_Layout_Analysis))

Now first of all I am not sure how I can pass the TextRegion ids in this command. How can I include those? Or how am I supposed to call the function?

Secondly for the argmuents donotblockseq and donotlineseg do I have to pass 0 if I don't want the blocks resp. lines to be segmented?

Would it might be possible to have an example command that specifies the collection, doc, page and region ids to run only the line segmentation on it?

Thank you a lot for your help and I am sorry if I understood something wrong.
Best,
Luca

**Comment by DRRV** [comment]
I will update the command line so that you can add the regions ids
it should be like this:
do_analyzeLayout COID DOCID/PAGEID --region=ID1,ID2,...,IDN  

If you want blockdetection(region) add --doRegionSeg
If you want bLineSeg add --doLineSeg 

(I  guess at least one is needed other nothing is done)

It is fine wrt your needs?

**Comment by lferrazzini95** [comment]
Hi,
Yes I think this is exactly what I wanted!
I will test it tomorrow and hopefully it will work :)
Thank you a lot for your help and your fast answers!
Best
Luca

**Comment by DRRV** [comment]
let me implement it first :)

**Comment by lferrazzini95** [comment]
Hi,
I am sorry to write you again. But I tried as you suggested and it didn't work. I run the following command from the command line:

`python TranskribusPyClient/src/TranskribusCommands/do_analyzeLayout.py 52380 313454/12394522 --doLineSeg True --region=rWNV9_1`

The error it returns me is that there is no option of --doLineSeg and --region
I am sorry if I understood something wrong. Thank you again for your help!
Best
Luca

**Comment by DRRV** [comment]
Let me push it  first . I will do it today.

**Comment by lferrazzini95** [comment]
Oh I am sorry, I didn't see you last comment! 
Please take your time :)

**Comment by DRRV** [comment]
can you try?  Pageid was a mistake, its the page number 
python TranskribusPyClient/src/TranskribusCommands/do_analyzeLayout.py 52380 313454/1  --region=rWNV9_1

**Comment by lferrazzini95** [comment]
Yes it works thank you a lot!
The only thing is that all lines are not assigned to any TextRegion structure type.
But I can do a script for myself that applies the structure type to the lines, if you want:)
Thank you again a lot for your work!

**Comment by DRRV** [comment]
it's weird: in my doc, the textlines are inside a textregion

**Comment by lferrazzini95** [comment]
In my doc the textlines are also in the TextRegion but they don't have the structure assigned to it (They appear in black instead of the corresponding color of the region). Probably it is not really important as they are correctly assigned to the TextRegion.
