### ISSUE TITLE
Get a list of all models

### ISSUE THREAD

**Issue by lferrazzini95** [Transkribus/TranskribusPyClient#7]
Hi,
I am currently trying to get a list of all available models which can be used for HTR.
I looked on the [documentation ](https://transkribus.eu/TrpServer/Swadl/wadl.html)and found the following API request:

'https://transkribus.eu/TrpServer/rest/modelslist'

I am using it as follows (in python):

```
payload = {'collId' : collId, 'userId' : userId, 'type' : 'PyLaia'}

r = requests.get('https://transkribus.eu/TrpServer/rest/modelslist?JSESSIONID={}'.format(sessionId), params = payload)
```
But it returns me the following server error (404):

```
<!doctype html><html lang="en"><head><title>HTTP Status 404 – Not Found</title><style type="text/css">body {font-family:Tahoma,Arial,sans-serif;} h1, h2, h3, b {color:white;background-color:#525D76;} h1 {font-size:22px;} h2 {font-size:16px;} h3 {font-size:14px;} p {font-size:12px;} a {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 404 – Not Found</h1><hr class="line" /><p><b>Type</b> Status Report</p><p><b>Message</b> Not Found</p><p><b>Description</b> The origin server did not find a current representation for the target resource or is not willing to disclose that one exists.</p><hr class="line" /><h3>Apache Tomcat/8.5.51</h3></body></html>
```
From the documentation I am not really sure what the type refers to (for now I assumed it refers to the technology.

I would be very happy if you could help me with this issue.
Thanks a lot!

Best,
Luca

**Comment by DRRV** [comment]
Have you tried: python TranskribusPyClient/src/TranskribusCommands/do_listHtrRnn.py  --colid=YOURCOLID

**Comment by lferrazzini95** [comment]
Thanks a lot for your fast reply!
I solved it by writing the following little function:

```
def getModelsList(colId, sessionId):
        r = requests.get('https://transkribus.eu/TrpServer/rest/recognition/{}/list?JSESSIONID={}'.format(colId, sessionId))
        models = r.text.split('name>')[1::2]
        for i in range(len(models)):
            models[i] = models[i].replace('</', '')
        return models
```

The for loop is not the most elegant way to extract the model names, but it is working as it should.
Best,

Luca
