### ISSUE TITLE
How to apply a model using the do_htrhmm.py script

### ISSUE THREAD

**Issue by lferrazzini95** [Transkribus/TranskribusPyClient#8]
Hi,

Sorry to bother you again...
I am trying to apply a selected model to an entire collection or selected documents of that collection (If I can do it for one document it is fine.).

I am not sure how the syntax resp. the arguments need to be defined when calling the script.

so I want something like:
```
python do_htrHmm.py --model_id 1234 --collId 1234 --docId 1234
```
Could you help me to find the correct argument description?

Thanks a lot!
Best,
Luca

**Comment by lferrazzini95** [comment]
Hi,

I figured out that I can just pass the arguments without naming them as follows:

```
python do_htrHmm.py "example_model_name" 1234 1234
```

But now I get the following errror:

```
Traceback (most recent call last):
  File "TranskribusPyClient/src/TranskribusCommands/do_htrHmm.py", line 110, in <module>
    jobid = doer.run(sModelName, colId, docId, sPages)
  File "TranskribusPyClient/src/TranskribusCommands/do_htrHmm.py", line 72, in run
    ret = self.rehtrDecode(colId, sModelName, docId, sPages)
AttributeError: 'DoHtr' object has no attribute 'rehtrDecode'
```
And I don't see where the rehtrDecode is implemented:
```
class DoHtr(TranskribusClient):
    sDefaultServerUrl = _Trnskrbs_default_url
    #--- INIT -------------------------------------------------------------------------------------------------------------    
    def __init__(self, trnkbsServerUrl, sHttpProxy=None, loggingLevel=logging.WARN):
        TranskribusClient.__init__(self, sServerUrl=self.sDefaultServerUrl, proxies=sHttpProxy, loggingLevel=loggingLevel)
    
    def run(self, sModelName, colId, docId, sPages):
        ret = self.rehtrDecode(colId, sModelName, docId, sPages)
        return ret
```

Thank you a lot for your help!

Best,
Luca

**Comment by DRRV** [comment]
htrHmm is no longer implemented in Transkribus (old HMM based model)

python do_htrRnn.py  MODELID None COLID  --docid DOCID

(The None parameter is for using a specific dictionnary)

**Comment by lferrazzini95** [comment]
Thanks a lot! It seems to work now!
Best,
Luca

**Comment by lferrazzini95** [comment]
Sorry I have one more issue with this method. When I submit the job it appears in transkribus, but when it finished I get the following error in the error window:
![image](https://user-images.githubusercontent.com/26362170/103891020-62325580-50e9-11eb-8ba4-4010f8833761.png)

Does this has something to do with the dictionary that can be passed? 
Do you know how I can fix this error?

Again, thank you a lot for your help!

Best,
Luca

**Comment by DRRV** [comment]
Does it work when you apply the model through the interface?

**Comment by lferrazzini95** [comment]
Yes it works when I run the job through the transkribus interface.

**Comment by DRRV** [comment]
same for me. I've never tested with the pylaia. I guess a parameter is missing (saying this is apylaia and not htr+). I will have a look

**Comment by DRRV** [comment]
I see with pylaia  it's POST/pylaia/{collId}/...   and with htr+ POST/recognition/{collId}/....
Pull!
python do_htrRnn.py MODELID None COLID --docid DOCID --**pylaia**

**Comment by lferrazzini95** [comment]
It worked!
Thanks a lot! :)
